services:
  fmhy_downloader:
    image: ghcr.io/vod-downloaders/fmhy-downloader:latest
    container_name: fmhy_downloader
    volumes:
      - ./config:/config
      - ./output:/output
    environment:
      - LOG_LEVEL=info
      - BRIDGE_URL=http://fmhy_bridge:3000/
      - FLARESOLVERR_URL=http://flaresolverr:8191/v1 # Optional
    ports:
      - 8080:8080
    restart: unless-stopped

  # This container contains the actual decryption logic for all
  # the backends and is seperate to keep the reverse-engineered code secret
  fmhy_bridge:
    image: ghcr.io/ggjorven/fmhy-bridge:latest
    container_name: fmhy_bridge
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  flaresolverr: # Optional
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
